apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: hassankalantari/simple-library-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:12345@db:5432/SimpleLibraryAppDB
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
